name: Install Dependencies

on:
  push:
    branches:
      - main

jobs:
  install-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2.4.0
        with:
          node-version: '14.x'

      - name: Install Dependencies
        run: npm install
